# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Proverbial Monkey
tagline:          ''
description:      'The cultivated thoughts of a crazy web developer from Leeds.<br /><a href="http://twitter.com/damianpoole">@damianpoole</a><br /><a href="http://github.com/damianpoole">GitHub</a><br /><a href="https://www.linkedin.com/in/damianpoole">Linkedin</a>'
url:              http://proverbialmonkey.co.uk

author:
  name:           'Damian Poole'
  url:            https://twitter.com/damianpoole

paginate:         5
